### ISSUE TITLE
Admob-ane issue

### ISSUE THREAD

**Issue by subramanya1989** [lilili87222/admob-for-flash#10]
Hi Sir,

I have used the ane working perfect on banner ads... I just have the problem with full ads event triggers perfectly and flash crashes. just solve my issue...

Log Status here --

admob ane log:status  code:onInterstitialReceivelevel:FULL_ADMOB_LEVEL

admob ane log:status  code:onInterstitialPresentlevel:FULL_ADMOB_LEVEL

Debug session terminated.

Thanks

Subramanya

**Comment by lilili87222** [comment]
maybe some error in your  code.e. you called exit() in flash deactive event app will exit.

**Comment by subramanya1989** [comment]
Nothing sir I never used exit code anywhere it just close as soon as the full ad present event triggers ... In banner ad there won't be any problem ... If you want I can send you my code as well .. Please help me ...

**Comment by lilili87222** [comment]
wohaosea@gmail.com

**Comment by subramanya1989** [comment]
Hi Sir,

I mailed the above contact till now no reply. Can you please do the needful...


Thanks...

**Comment by lilili87222** [comment]
I have not receive your attachment.

**Comment by lilili87222** [comment]
your demo code appear that error or your apk.

**Comment by subramanya1989** [comment]
Thanks Its working fine sorry for the miss.... And just a doubt is there any option to change the width and height of the Admob banner ???

**Comment by lilili87222** [comment]
you can find all admob banner size in www.admob.com.
