### ISSUE TITLE
Does this ANE support Android-x86 yet?

### ISSUE THREAD

**Issue by hybridmindset** [lilili87222/admob-for-flash#11]
Have you re-compiled the ane with support for x86 Android yet?

**Comment by lilili87222** [comment]
not support x86.if need I can add it.

**Comment by hybridmindset** [comment]
Yes x86 support is needed. It is simply changing the extensions.xml file and re-compiling with the latest AIR ADT to support it.

**Comment by lilili87222** [comment]
upgraded
