### ISSUE TITLE
Compile Issue With New Packager For IOS

### ISSUE THREAD

**Issue by hybridmindset** [lilili87222/admob-for-flash#12]
Everytime I try to package for IOS using the new faster packager for Adobe AIR with this ANE it never works for IOS. I always get a duplicate symbol error:

[java] duplicate symbol _traits:so.cuo.platform.admob::AdmobFunNames$ in:
     [java]     AOTBuildOutput-0000000000_17_1.o
     [java]     so.cuo.platform.admob-0_0_1.o
     [java] duplicate symbol _traits:so.cuo.platform.admob::AdmobFunNames in:
     [java]     AOTBuildOutput-0000000000_17_1.o
     [java]     so.cuo.platform.admob-0_0_1.o

[java] Compilation failed while executing : ld64
     [java] ld: 2 duplicate symbols for architecture armv7

**Comment by lilili87222** [comment]
not use faster package.  and download the last version.

**Comment by hybridmindset** [comment]
We have to start using the faster packager it is the default compiler now going forward. Why don't you recompile the ANE correctly or release the source so someone else can re-compile it. Otherwise this becomes useless.

**Comment by lilili87222** [comment]
download the last version try again. we have used it for month.

**Comment by hybridmindset** [comment]
I've tested the latest ANE and it keeps throwing the duplicate symbol error. Are you using new packager with the -useLegacyAOT true flag? Are you compiling for IOS? This only happens for IOS. Please fix. Its just a simple re-compile.

**Comment by lilili87222** [comment]
upgraded
