### ISSUE TITLE
Require universal ios libraries

### ISSUE THREAD

**Issue by fandlr** [lilili87222/admob-for-flash#13]
Air 16.0.0.259 for iOS
Ane admob_all_in_one_6.12.2

It popuped an error window :
"
Error:META-INF/ANE/iPhone-ARM/admob4.0.a are required to have universal iOS libraries.Please contact the ANE developer(s) to get the same.
"

**Comment by lilili87222** [comment]
download again,the last upgrade have support ios 64

**Comment by lilili87222** [comment]
upgraded.

**Comment by andreyok** [comment]
Air 17.0.0.138
Ane admob_all_in_one_6.12.2.ane || admob_all_in_one_20150209.ane || admob_without_gps_20150209.ane

---------------------------
Adobe Flash Professional
---------------------------
Error creating files.

Error: META-INF/ANE/iPhone-ARM/admob4.0.a are required to have universal iOS libraries. Please contact the ANE developer(s) to get the same.


---------------------------
ОК   
---------------------------
