### ISSUE TITLE
iOS Publishing: Error creating files on AIR 33.1.1.190

### ISSUE THREAD

**Issue by sairope** [lilili87222/admob-for-flash#130]
I'm getting a lot of error when publishing for iOS. Tested on admob_all_in_one_20200525. Even when downgrading SDK to 33.0.2 the same errors occur.

https://imgur.com/a/hBhRGnb

**Comment by Safromanowitch** [comment]
Maybe it is connected to the Bug about the minimum OS Version like here (https://github.com/lilili87222/admob-for-flash/issues/113#issuecomment-660525256)?

**Comment by sairope** [comment]
I've resolved the errors by updating Animate CC to the latest version. However, this might have been caused by some library bug because I hadn't had this issue before.
