### ISSUE TITLE
iOS 8 position problem

### ISSUE THREAD

**Issue by Laur3nt1u** [lilili87222/admob-for-flash#14]
I have a banner positioned bottom center on android is working fine but on iPad with iOS 8.0.2 the banner is not positioned correctly(unity3d had a also a problem with ios8 and landscape rotation)

![img_0161](https://cloud.githubusercontent.com/assets/760300/5832541/9d945858-a14f-11e4-86d2-db06a0582669.PNG)
![img_0163](https://cloud.githubusercontent.com/assets/760300/5832542/9e16980e-a14f-11e4-89c7-3d9d713bd6e8.PNG)
![img_0162](https://cloud.githubusercontent.com/assets/760300/5832544/a0f87d58-a14f-11e4-9b6b-9f3628bab0b3.PNG)
![img_0164](https://cloud.githubusercontent.com/assets/760300/5832545/a29970e0-a14f-11e4-9b8d-14fd0c876828.PNG)

**Comment by lilili87222** [comment]
this is a bug of air sdk 16. I may try to fix it in ane after 2.1 if adobe not fix this bug.
