### ISSUE TITLE
admob 20150126 crash on ipad ios 7

### ISSUE THREAD

**Issue by lilili87222** [lilili87222/admob-for-flash#15]
admob 20150126 crash on ipad ios 7.  I am trying to fix it .

**Comment by lilili87222** [comment]
I found it is a bug of air 16.  app will crash when add ane  with armv64 .I just test adobe game sdk ane. all is the same.

**Comment by lindagattino** [comment]
so we have to wait for an other sdk from Apache?

**Comment by lilili87222** [comment]
yes ,we have to wait for an other sdk from adobe.

**Comment by lindagattino** [comment]
I see... I hope it will be in a little while. I found the 4.14 on apache site, is that the last one? Or now it's again an Adobe product?

**Comment by lilili87222** [comment]
air sdk is a product of adobe.
flex sdk is a product of apache.
it is a bug of air sdk. 
air sdk is a part of flex sdk .

**Comment by lilili87222** [comment]
air sdk is a product of adobe.
flex sdk is a product of apache.
it is a bug of air sdk. 
air sdk is a part of flex sdk .

**Comment by lindagattino** [comment]
but apache air and adobe air packages are the same?
i don’t understand why they decided to spit…. and I noticed that Adobe did not contribute anymore to air package, am I wrong?

Linda Gattino.
Cell: 349 88 51 155.
Tel/fax: 0125 19 60 534.
Email: info@lindagattino.it.
Www: http://www.lindagattino.it.
Skype: lindagattino.
LinkedIn: http://it.linkedin.com/in/gattino.

Il giorno 05/feb/2015, alle ore 04:45, lilili87222 <notifications@github.com> ha scritto:

**Comment by WHAmarcelo** [comment]
Lili, can you please update recent compiled ANE but without GP versions also?

Cheers

**Comment by lilili87222** [comment]
### admob_ane_20150209 changes
1.upgrade admob sdk to 7.0<br/>
2.fix banner position problem completely.tested on ios 7,io8 and ios 6 with air 17 beta.

**Comment by WHAmarcelo** [comment]
@lilili87222 can you please update also the ANE without GPS with this latest version? or at least leave some basic instructions for me to try to compile it without GPS? Current version is conflicting with GPS ANE that I'm Using (https://github.com/overlawled/ANE-Google-Play-Game-Services). Thanks!

**Comment by lilili87222** [comment]
admob without gps updated.
@WHAmarcelo 

if you like it ,you can donate or download our game and review it.

**Comment by WHAmarcelo** [comment]
which your game is?

**Comment by lilili87222** [comment]
https://itunes.apple.com/us/artist/phonegame/id553087275?mt=8
