### ISSUE TITLE
Banner height are different by Android devices with different dpi screen?

### ISSUE THREAD

**Issue by thanks1234** [lilili87222/admob-for-flash#17]
Hi, 

Thanks you so much for creating such a great ane.
I am wondering.

function onAdReceived(event:AdmobEvent):void
{
    if(event.type==AdmobEvent.onBannerReceive){
    trace(event.data.width,event.data.height);
    }
}

When I choose to use Admob.SMART_BANNER, and
When an app receive the height, 
Will the height be different depending on the dpi of each android devices?

such as
hdpi
xhdpi
xxhdpi

For retina in iOS, the height needs to be 2 time heigher to make it work properly.
if event.data.height is 50, to fit with the banner, the value needs to be 100.

Are there any difference or for Android, event.data.height should be correct on all the Android devices?
Should I need to add some number to get proper value?

**Comment by lilili87222** [comment]
Admob.SMART_BANNER  Will the height be different depending on the dpi of each android devices

you can choose Admob.Banner. that height will be fixed.

**Comment by thanks1234** [comment]
Beautiful thanks!
