### ISSUE TITLE
admob_without_gps_20150209, cant see a banner

### ISSUE THREAD

**Issue by smival** [lilili87222/admob-for-flash#18]
I am trying to use admob_without_gps because another versions has compatibility errors with Google Play Services ANE. Why I cant see a benner using admob_without_gps? Anover version works fine but only without Google Play Services ANE.

**Comment by lilili87222** [comment]
maybe your gp service lib is too old.

**Comment by smival** [comment]
My general trouble is admob_all_in_one_20150209.ane and admob_all_in_one_6.12.2.ane has a conflict with another ANEs in my project as such as Google Play services, Chartboost and another. I got following errors when I try to build the project:
```
Create Android Package
dx tool failed:
UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.IllegalArgumentException: already added: Lcom/google/ads/AdRequest$ErrorCode;
	at com.android.dx.dex.file.ClassDefsSection.add(ClassDefsSection.java:123)
	at com.android.dx.dex.file.DexFile.add(DexFile.java:143)
	at com.android.dx.command.dexer.Main.processClass(Main.java:301)
	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:278)
	at com.android.dx.command.dexer.Main.access$100(Main.java:56)
	at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:229)
	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:244)
	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:130)
	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:108)
	at com.android.dx.command.dexer.Main.processOne(Main.java:247)
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:183)
	at com.android.dx.command.dexer.Main.run(Main.java:139)
	at com.android.dx.command.dexer.Main.main(Main.java:120)
	at com.android.dx.command.Main.main(Main.java:89)
1 error; aborting
```

**Comment by CodyTolene** [comment]
You can't see your banner because you need to direct google play services to the 'gps free' from another ANE (that already has the gps) somehow. I am trying to figure that out how to do that right now as well.. The reason you got the conflicts between the ANE's [ admob_with_gps & your other ANE ] is because they both include gps. If you were to take the AdRequest$ErrorCode.java out of your ANE then the next error would point to the next ad class that was already imported previously.

**Comment by CodyTolene** [comment]
As seen here the differences inside ANE
![capture](https://cloud.githubusercontent.com/assets/7137181/7060542/8123fb3e-de48-11e4-83be-2193b997c2bb.PNG)

**Comment by lilili87222** [comment]
if you use  add other ane include gps lib then use admob_without_gps_20150209.ane else use  admob_all_in_one_20150209.ane. 
and config must add to xxx-app.xml
<meta-data android:name="com.google.android.gms.version"
        android:value="@integer/google_play_services_version" />
                   <activity android:name="com.google.android.gms.ads.AdActivity" android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|uiMode|screenSize|smallestScreenSize"/>

**Comment by CodyTolene** [comment]
When I used admobe without gps, the ads do not show up as they do when using all in one.
How do I used admob_without_gps.ane without gps? From what I read in the description is to use the without_gps file if another ane has gps in it.. However, the file without gps still does not work when you do that

**Comment by smival** [comment]
finally it works, looks like I had a double lines of this for different ANEs
```
<meta-data android:name="com.google.android.gms.version"  android:value="@integer/google_play_services_version" />
```
as lilili87222 said, a Chartboost and a Google Play Game Services (achivements) has a GPS code (?) and this is a reason why we need to use "without_gps" version of admob ANE.
By the way Adcolony has no some conflicted code and if you use Adcolony+Admob only you gonna take admob_all_in_one_20150209.ane.

**Comment by NathanFitchett** [comment]
This still doesnt work for me I dont understand I am using the without GPS and everything works fine with no errors but no ads show up I cant see any of them. I know they are there but they wont display. I am using Adobe AIR 17.0 and AS3

**Comment by NathanFitchett** [comment]
My XML: 

<application>
 
        <meta-data android:name="com.google.android.gms.version"
        android:value="@integer/google_play_services_version" />
        <activity android:name="com.google.android.gms.ads.AdActivity" android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|uiMode|screenSize|smallestScreenSize"/>
</application>

**Comment by NathanFitchett** [comment]
<application>
 
        <meta-data android:name="com.google.android.gms.version"
        android:value="@integer/google_play_services_version" />
        <activity android:name="com.google.android.gms.ads.AdActivity" android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|uiMode|screenSize|smallestScreenSize"/>
</application>

**Comment by NathanFitchett** [comment]
My XML Is

<application>
 

        <meta-data android:name="com.google.android.gms.version"
        android:value="@integer/google_play_services_version" />

        <activity android:name="com.google.android.gms.ads.AdActivity" android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|uiMode|screenSize|smallestScreenSize"/>
</application>

**Comment by lilili87222** [comment]
add event listener and trace fail event info
