### ISSUE TITLE
required to have universal iOS libraries

### ISSUE THREAD

**Issue by andreyok** [lilili87222/admob-for-flash#20]
Air 17.0.0.138
 Ane admob_all_in_one_6.12.2.ane || admob_all_in_one_20150209.ane || admob_without_gps_20150209.ane

Adobe Flash Professional

Error creating files.

Error: META-INF/ANE/iPhone-ARM/admob4.0.a are required to have universal iOS libraries. Please contact the ANE developer(s) to get the same.

ОК

**Comment by lilili87222** [comment]
download and try again .your file is a old version.

**Comment by andreyok** [comment]
No, it isn't a reason.
New projects create good, but if you will try to change old .ane to new one, you have the error. And only renaming of .fla can help to avoid the error. And if you will rename .fla to old name you get an error again.
I think it's one of many errors of Flash CS6.

**Comment by suman34677** [comment]
Thanks...  @andreyok  its working fine
