### ISSUE TITLE
context does not have a method with the name...

### ISSUE THREAD

**Issue by raduev** [lilili87222/admob-for-flash#25]
Hello, i get the error on Android, admob 20150209 base on ios sdk 7.0,android sdk 6.5
Error #3500: The extension context does not have a method with the name admobShowBanner, and admobHideBanner.
in IOS work fine, tnx

**Comment by lilili87222** [comment]
have you try admob_all_in_one_20150519.ane?

**Comment by raduev** [comment]
yes, this work, tnx
