### ISSUE TITLE
Native Application losing focus on tapping banner

### ISSUE THREAD

**Issue by rams771987** [lilili87222/admob-for-flash#28]
i have back button functionality in my game. if i tap on banner then back button on devise, the app getting minimized. can u help me to solve this issue..

**Comment by lilili87222** [comment]
the app getting minimized? how to minimized?

**Comment by rams771987** [comment]
sorry for my bad English. Let me explain u clearly. I had added a keyboard event listener on nativeApplication. In general if i tap back button on devise, this function execute perfectly and shows exit alert. But if i tap on banner then tapping on back button results deactivating the application. I have to tap on the game icon my devise menu to reactivate. Here some of my code...

NativeApplication.nativeApplication.addEventListener(KeyboardEvent.KEY_DOWN, handleKeys);
private function handleKeys(event:KeyboardEvent):void
		{
			if (event.keyCode == Keyboard.BACK)
			{
				event.preventDefault();
				event.stopImmediatePropagation();
                                showAlert();
                         }
                }

This function is not executing if tap on back button after tapping banner...


Thank you

**Comment by lilili87222** [comment]
Click BACK after tapped banner ad, the focus has been lost, unable to handler event after the back key,so  the problem you mentioned is unabled to solve
