### ISSUE TITLE
Packaging issue with AIR SDK 18

### ISSUE THREAD

**Issue by mohammedwaris** [lilili87222/admob-for-flash#30]
I am getting following error while packaging.... any idea ?

META-INF/ANE/iPhone-ARM/admob4.0.a are required to have universal iOS libraries. Please contact the ANE developer(s) to get the same.

**Comment by lilili87222** [comment]
have you upgrade to the last version?

**Comment by mohammedwaris** [comment]
I tried to package with all the below ANE yesterday, but none worked.

lilili87222/admob-for-flash/admob_ane_ios_android/anes/admob_all_in_one_20150519.ane
lilili87222/admob-for-flash/admob_ane_ios_android/anes/admob_all_in_one_6.12.2.ane
lilili87222/admob-for-flash/admob_ane_ios_android/anes/admob_without_gps_20150519.ane

**Comment by lilili87222** [comment]
admob4.0.a is a file of old version,so you are using a error file. there is no file named admob4.0.a in new version

**Comment by mohammedwaris** [comment]
Can you give the download link for the new version.

**Comment by lilili87222** [comment]
https://github.com/lilili87222/admob-for-flash/blob/master/admob_ane_ios_android/anes/admob_all_in_one_20150519.ane?raw=true
