### ISSUE TITLE
Does the plugin support Admob mediation?

### ISSUE THREAD

**Issue by khambadkone** [lilili87222/admob-for-flash#31]
is the plugin specifically for Admob Ad Network, or can it support mediation of other networks?

if it supports mediation, please specify how to add the libraries of other ad networks to the app ?

If not, request you to clarify on your README.

**Comment by lilili87222** [comment]
mediation need compile other network libraries  to the ane witch will enlarge the target file, and not freedom to choice network.
recommend try  https://github.com/lilili87222/as3-air-ad-network-framework

**Comment by khambadkone** [comment]
I dont mind the file size.  How can I add Vungle, iAd and Millenial Media,
and have it mediated by Admob ?

Mahesh Khambadkone
Co-Founder - Games2win

*We're hiring a Senior Tech Lead
<https://www.linkedin.com/jobs2/view/44966576> *

**Comment by lilili87222** [comment]
Let me try

**Comment by lilili87222** [comment]
Admob Mediation need mediation ID, but I can not find any mediation ID in mediation setting page(admob document said it is in this page),can you find where is the mediation ID?
