### ISSUE TITLE
Error Creating Files

### ISSUE THREAD

**Issue by cahyasatrio** [lilili87222/admob-for-flash#32]
I use admob_all_in_one_20150519, but when I publish error.
"Error Creating Files. NameSpace is invalid in the application descriptor file."

and when I was running "Test Movie terminated.
The content can not be loaded Because there was a problem loading an extension: Error: Extension namespace is invalid for the C: \ docume ~ 1 \ xxx \ Locals ~ 1 \ Temp \ Tmp_ANE_File_Unzipped_Packages \ admob_all_in_one_20150519.ane "
I use Windows XP & AdobeAir 18

How to fix it?
Thank

**Comment by lilili87222** [comment]
Error Creating Files. NameSpace is invalid in the application descriptor file. your xxx-app.xml is error.
