### ISSUE TITLE
Crash with interstitial

### ISSUE THREAD

**Issue by yvant** [lilili87222/admob-for-flash#33]
Hi, 

I used the admob_all_in_one_20150519.ane to add ads in my mobile game. It works really great with banners, but crashes when I try to add full screen interstitials. I used the tutorial and the app just crashes immediately on a samsung gs3, an iPad mini and an iPhone 4 each time the ad has to be displayed. Is there something that needs to be done? I added the number of my interstital ad too.

Thanks

**Comment by gskgrek** [comment]
It works fine on my iPhone 5s :>
Do you check supportDevice and recived events?
Do you have other anes using google play services?

**Comment by yvant** [comment]
Well actually it works fine now... I just placed it at another place in the app. I guess that I had a memory leak issue. Sorry for the bother :(

**Comment by yvant** [comment]
Is it possible to get add an event to know when the interstitial is closed by the user?

**Comment by lilili87222** [comment]
event type is in class AdmobEvent
