### ISSUE TITLE
The Ad is not appearing

### ISSUE THREAD

**Issue by Greenbald** [lilili87222/admob-for-flash#34]
I do not know why, but the ad is just not showing in the screen. I used the demo.as(in your source examples) and tested it myself in my android, and its not showing. Can you please help me?

I'm using AIR SDK 18 for android.

For example, i know that the code is executing : 
     xPositionValue = 0
     yPositionValue = 0
     admob.showBannerAbsolute(adsize, xPositionValue, yPositionValue, extraParam);

And the device is supported, but the ad is still not showing, not even a part of it.

Maybe it's not showing because my app is not in the play store? There's a section in AdMob website that requires me to create a Ad unit ID, ca-app-pub-XXXXXXXXXXXXXXXX/XXXXXXXXXX, so i need to link my app in google play to really show the ad? I was using some random ID.

Thank you for your time =)

**Comment by lilili87222** [comment]
not need in play store. you need set you xxx-app.xml if you are build a apk.
