### ISSUE TITLE
Invalid namespace http://ns.adobe.com/air/extension/15.0

### ISSUE THREAD

**Issue by rubel** [lilili87222/admob-for-flash#36]
Namespace is invalid in the application descriptor file.

/Users/rubel/Library/Caches/TemporaryItems/AndroidFlappyBirdEscape_ANE_Cache/admob.ane [META-INF/ANE/extension.xml]: error 102: Invalid namespace http://ns.adobe.com/air/extension/15.0

**Comment by lilili87222** [comment]
upgrade air sdk to 17 or later,change xml http://ns.adobe.com/air/extension/17.0
