### ISSUE TITLE
how to show test ad banner for iOS

### ISSUE THREAD

**Issue by ulsan1635** [lilili87222/admob-for-flash#37]
Hi~

I read readme.md and sample code.

I typed the following code :
extraParam.testDeviceID="my devide UDID"; for ios 

But I can not see the test ad banner for iOS.

What seems to be the problem?
Is there anyone who knows how to show test ad banner for iOS?

Thank in advance.

**Comment by lilili87222** [comment]
it is hard for air developer to get ios device udid ,just
delete  extraParam.testDeviceID="my devide UDID"
to display normal ad.
