### ISSUE TITLE
Ad doesn't show

### ISSUE THREAD

**Issue by crazycute** [lilili87222/admob-for-flash#39]
Hi there! I'm not sure why, I tried everything that is possible but in the end I have the same problem. Each time I call for a smart banner, i get no ad. 

"admob ane log:status  code:onBannerReceivelevel:0_0", 0 width and 0 height.

Tried with different admob banner keys that I know they work, updated air from 19 to 20, tried with admob_all_in_one and tried with no_gps too. It doesn't want to show ads. 
Any suggestions? Anyone else happen to get this problem? 
Please help.

**Comment by lilili87222** [comment]
start banner may not work on some device

**Comment by lilili87222** [comment]
try Admob.Banner to test
