### ISSUE TITLE
Duplicate symbol l017

### ISSUE THREAD

**Issue by pitanello** [lilili87222/admob-for-flash#43]
Hello
Do you know how i can fix this problem in your Ane?
Thanks a lot

![admobissue](https://cloud.githubusercontent.com/assets/11668850/14251220/3fb28588-fa82-11e5-8b06-96104207bf9a.jpg)

**Comment by lilili87222** [comment]
use air 20 or later

**Comment by pitanello** [comment]
This is with AIR20, i can't use AIR21 because i get the "Invalid Signature" for the binary from the AppStore. ([iOS][Win] IPA packaged on Windows machine cannot be submitted to the Apple App store. Error "This build is invalid" occurs in iTunes connect).

![admobissueair20](https://cloud.githubusercontent.com/assets/11668850/14276723/323b411c-fb20-11e5-9c97-40c84de37f65.jpg)

**Comment by lilili87222** [comment]
are you using air20 release ? air 20 beta  wil cause this bug too

**Comment by lilili87222** [comment]
are you using air20 release ? air 20 beta  wil cause this bug too
