### ISSUE TITLE
Invalid Namespace

### ISSUE THREAD

**Issue by valcarni** [lilili87222/admob-for-flash#44]
Hi... The last version of your ANE that I have been able to get working is admob_all_in_one_6.12.3.ane

I have tried admob20160127.ane and admob20160409.ane and neither of these work as they say invalid namespace.  

I am currently using Adobe Air 22.0.  I have tried air 21, 20 and 17 with this and none of those work.  I am using Flash builder 4.6 and it doesn't work for either ios or android build, when i press play, it says namespace or library.swf error... but then when i change the ane back to admob_all_in_one_6.12.3.ane it starts working again.... reason I want to try the new ANE is because the adverts work on ios correctly, but they don't for me on android... like the ad will load, but it never changes.

**Comment by valcarni** [comment]
I have the updated namespace in the XML each time i change adobe air version as well.. so i have no idea why it's saying there is a problem.  I'm hoping the new versions will fix the problem on android with refreshing of the adverts.

**Comment by lilili87222** [comment]
may been you can try set compile param   -swf-version 35

**Comment by valcarni** [comment]
In my "additional compiler arguments" in Flash Builder i put and it doesn't run
-locale en_US -swf-version 35

i've never really played around with the parameters before

**Comment by valcarni** [comment]
I changed it to -swf-version 32 and it works now... weird... maybe I might be missing some files in my adobe air ?

**Comment by lilili87222** [comment]
flash lib may not updated
