### ISSUE TITLE
Air 22 SDK Beta iOs error

### ISSUE THREAD

**Issue by exlex84** [lilili87222/admob-for-flash#46]
Hi, It seems that there is an error with the latest version of Adobe Air. That version is mandatory if you want to compile ios 9 apps on windows because previous versions (20, 21) have a signing error. In my case, interstitial doesn´t show but the debugger says "admob ane log:status  code:onInterstitialPresentlevel:onInterstitialPresent"

Same app compiled with sdk 21 works ok (but itunes connect launch that signing error)

Thank you.

**Comment by Gamezhero** [comment]
I did not try in 22, but compile in 19 and submit to iTunes w/o problem.

**Comment by lilili87222** [comment]
does not 20 works?

**Comment by Gamezhero** [comment]
I don't know what host of admob and added some - works great

<key>admob.com</key>
	        <dict>
	            <key>NSExceptionAllowsInsecureHTTPLoads</key><true/>
	            <key>NSIncludesSubdomains</key><true/>                
	            <key>NSExceptionRequiresForwardSecrecy</key><false/>
	        </dict>
         <key>google.com</key>
	        <dict>
	            <key>NSExceptionAllowsInsecureHTTPLoads</key><true/>
	            <key>NSIncludesSubdomains</key><true/>                
	            <key>NSExceptionRequiresForwardSecrecy</key><false/>
	        </dict>
         <key>adsense.com</key>
	        <dict>
	            <key>NSExceptionAllowsInsecureHTTPLoads</key><true/>
	            <key>NSIncludesSubdomains</key><true/>                
	            <key>NSExceptionRequiresForwardSecrecy</key><false/>
	        </dict>
         <key>googlesyndication.com</key>
	        <dict>
	            <key>NSExceptionAllowsInsecureHTTPLoads</key><true/>
	            <key>NSIncludesSubdomains</key><true/>                
	            <key>NSExceptionRequiresForwardSecrecy</key><false/>
	        </dict>
         <key>doubleclick.net</key>
	        <dict>
	            <key>NSExceptionAllowsInsecureHTTPLoads</key><true/>
	            <key>NSIncludesSubdomains</key><true/>                
	            <key>NSExceptionRequiresForwardSecrecy</key><false/>
	        </dict>
         <key>doubleclickbygoogle.com</key>
	        <dict>
	            <key>NSExceptionAllowsInsecureHTTPLoads</key><true/>
	            <key>NSIncludesSubdomains</key><true/>                
	            <key>NSExceptionRequiresForwardSecrecy</key><false/>
	        </dict>

**Comment by Gamezhero** [comment]
But I have other problem with ANDROID
I can't make build.
W/o ANE build makes great
http://prntscr.com/b56atj

**Comment by lilili87222** [comment]
remove google play services ane

**Comment by lilili87222** [comment]
air 20 or later required add 
https://github.com/lilili87222/admob-for-flash#for-ios-add-network-permission-nsapptransportsecurity

**Comment by Gamezhero** [comment]
How I can use Google Play Services w/o conflict with this ANE?

**Comment by lilili87222** [comment]
remove google play services ane or use admob_without_gps.ane

**Comment by lilili87222** [comment]
upgraded
