### ISSUE TITLE
admob20160127_without_gps.ane problems on ANDROID

### ISSUE THREAD

**Issue by Gamezhero** [lilili87222/admob-for-flash#47]
I used well - admob20160409.ane
But add to project Google Game Service and got conflict with admob20160409.ane
I use admob20160127_without_gps.ane but have problem:

I see trace

> admob 20160127 base on ios sdk 7.6,android sdk 8.1

I have this message after `admob.cacheInterstitial();`
http://prntscr.com/b7smkb

and try show banner
http://prntscr.com/b7t6ov

My Settings:

* AIR 22 (16 May)
* -swf-version 33
* http://prntscr.com/b7snz3
* http://prntscr.com/b7sods
* http://prntscr.com/b7sp51

I used myflashlab ANE with Google Game Service v8.4, you used v8.1
Maybe need to update admob20160127_without_gps.ane to last version?

**Comment by lilili87222** [comment]
maybe ,I will try to test

**Comment by Gamezhero** [comment]
Will be great, thanks

**Comment by Gamezhero** [comment]
any news?

**Comment by lilili87222** [comment]
handing....

**Comment by Gamezhero** [comment]
handing...?

**Comment by lilili87222** [comment]
will support native ad

**Comment by Gamezhero** [comment]
does ane suppor Google Game Service v9.0 or only next step v8.4?

**Comment by lilili87222** [comment]
upgraded
