### ISSUE TITLE
Does admob20160409 support IPv6?

### ISSUE THREAD

**Issue by ulsan1635** [lilili87222/admob-for-flash#48]
Apple declared that as of June 1 all apps submitted to the AppStore MUST support IPv6-only networking.

This is found in the the following link :
https://developer.apple.com/news/?id=05042016a

Does admob20160409 support IPv6?

**Comment by lilili87222** [comment]
yes,because air and admob used domain,not ip

**Comment by ulsan1635** [comment]
Thank you very much.
