### ISSUE TITLE
Does it supports new native express ads?

### ISSUE THREAD

**Issue by MudasirBhutto** [lilili87222/admob-for-flash#49]
Hello all,

Does it supports new native express ads? https://support.google.com/admob/answer/6270315?ctx=ui&hl=en

If no, then when this feature will be implemented?

Thanks in advance.

**Comment by lilili87222** [comment]
yes

**Comment by MudasirBhutto** [comment]
Thanks lilili87222.
How we can add native express ads? Because I only see the Banner and Interstitial in API, not native express ads. Can you help me? Piece of code would be helpful. Thanks.

**Comment by lilili87222** [comment]
native ad will  in days.

**Comment by MudasirBhutto** [comment]
how many days? Are you updating the ane for native ads support?

**Comment by lilili87222** [comment]
yes

**Comment by MudasirBhutto** [comment]
Ok, thanks. Waiting for this cool feature.

**Comment by lilili87222** [comment]
committed

**Comment by MudasirBhutto** [comment]
Thanks man...! I am downloading it, let me check it, thanks once again.
