### ISSUE TITLE
android-support-v4重复，能否提供一个不包含的ane

### ISSUE THREAD

**Issue by PandaFang** [lilili87222/admob-for-flash#52]
我的工程中使用了多个ane ,其他的ane已经包含了android-support-v4 ， 打包会提示里面的class重复，劳烦再上个不含它的

**Comment by lilili87222** [comment]
使用no gps版本试试

**Comment by PandaFang** [comment]
使用 without_gps版 放在 demo中 ，打包时出现这样的一堆错误
打包应用程序时出错:
aapt tool failed:C:\Users\PANDAF~1\AppData\Local\Temp\9e6094a0-424b-46a6-a1f1-9ed4740be796\app_entry_res\values\strings.xml:19: error: Resource at app_version appears in overlay but not in the base package; use <add-resource> to add.

C:\Users\PANDAF~1\AppData\Local\Temp\9e6094a0-424b-46a6-a1f1-9ed4740be796\app_entry_res\values\strings.xml:20: error: Resource at button_install appears in overlay but not in the base package; use <add-resource> to add.

C:\Users\PANDAF~1\AppData\Local\Temp\9e6094a0-424b-46a6-a1f1-9ed4740be796\app_entry_res\values\strings.xml:21: error: Resource at button_exit appears in overlay but not in the base package; use <add-resource> to add.

C:\Users\PANDAF~1\AppData\Local\Temp\9e6094a0-424b-46a6-a1f1-9ed4740be796\app_entry_res\values\strings.xml:22: error: Resource at title_adobe_air appears in overlay but not in the base package; use <add-resource> to add.
……

奇怪的是， 放在我的工程中打包正常。 但是没有banner显示
我不使用与all in one 冲突的ane测试，显示了banner
