### ISSUE TITLE
Banner sizes that arent clickable

### ISSUE THREAD

**Issue by dd410** [lilili87222/admob-for-flash#53]
Banners with this sizes aren't clickable. After clicking banner nothing happens.
BANNER_468X60
BANNER_STANDARD
SMART_BANNER

I use ANE with GPS 2016

Also one more question how to reload banner to get new add ? I tryed to hidde and show it again few times but that doesnt work.

**Comment by lilili87222** [comment]
ios or android? air version,os version.

**Comment by dd410** [comment]
Android version. I didnt tested iOS.

**Comment by lilili87222** [comment]
your air version?

**Comment by lilili87222** [comment]
test with air 22 ,works well.
