### ISSUE TITLE
admob_without_gps not compatible with face detection

### ISSUE THREAD

**Issue by AlexUrrutia** [lilili87222/admob-for-flash#60]
I combine this admob ANE with a face detection ANE: https://github.com/marpies/face-detection-ane

it compiles but is not showing ads, if I add the AdMob all in one ANE, it won't compile, gives some errors about google play services...

**What are the exact dependencies required when using the ANE without play services?**

Thanks!

**Comment by lilili87222** [comment]
You can add event listener and log to trace the reason.
