### ISSUE TITLE
New feature: mute sound

### ISSUE THREAD

**Issue by pozirk** [lilili87222/admob-for-flash#63]
Hello!

First, I want to say thank you for making and sharing this great extension with everyone.
I'm using it and very happy with the functionality.

I have a situation, when users play my games muted and they want ads to be muted as well.
AdMob SDK provide this feature:
`setAppMuted(boolean muted);`
https://firebase.google.com/docs/reference/android/com/google/android/gms/ads/MobileAds

Could you please add this feature to your extension?
I'm sure this feature will be beneficial for you and your games as well.

Thank you!

**Comment by lilili87222** [comment]
OK,I try to add the next version.

**Comment by pozirk** [comment]
Thank you!

**Comment by pozirk** [comment]
Any ideas when your next version will be released? :)

**Comment by lilili87222** [comment]
Updated ,but it seems not take any effect

**Comment by pozirk** [comment]
Hm...
There is also `setVolume();` method, it worked fine for me under Android.
For example, `setVolume(0);` muted ads completely.
Do you want to try it?

**Comment by pozirk** [comment]
@lilili87222, any update?
Have you tried setVolume()?
Thank you! :)

**Comment by lilili87222** [comment]
added

**Comment by pozirk** [comment]
Thanks a lot, works perfectly! :)
