### ISSUE TITLE
Ad is not showing

### ISSUE THREAD

**Issue by hypesol** [lilili87222/admob-for-flash#71]
I am successfully added ane in  my project and everything is fine but ads are not showing. I am using temp Id which I got from android's official website. My app is running fine even not giving any kind of error. Here is my code please let me know why ads are not showing. Thanks	

import flash.display.Sprite;
	import so.cuo.platform.admob.*;
			var admob:Admob= Admob.getInstance();
			if(admob.supportDevice){
				trace("YES");
				admob.setKeys("1072772517","ca-app-pub-3940256099942544");
				Admob.getInstance().showBanner(AdmobSize.BANNER_320x50,AdmobPosition.BOTTOM_CENTER);
							}
			else{
					trace("NO");
				}

**Comment by hypesol** [comment]
NO RESPONSE

**Comment by hypesol** [comment]
Can anyone help me for this issue. I tried once again this code but nothing display there just blank screen.

import so.cuo.platform.admob.*;
var bannerAdUID:String = "ca-app-pub-3940256099942544/6300978111";
var intersAdUID:String = "ca-app-pub-3940256099942544/1033173712";
Admob.getInstance().setKeys(bannerAdUID,intersAdUID);
//Admob.getInstance().showBanner(AdmobSize.BANNER_320x50,AdmobPosition.BOTTOM_CENTER);
if(Admob.getInstance().supportDevice){
	txt.text = "Supported";
	Admob.getInstance().showBanner(AdmobSize.SMART_BANNER,AdmobPosition.BOTTOM_CENTER);
}
else{
txt.text = "Not Supported";	
	}
Admob.getInstance().cacheInterstitial(); 
if (Admob.getInstance().isInterstitialReady()) {
      Admob.getInstance().showInterstitial();
    }

**Comment by lilili87222** [comment]
1.Try change Smart banner to AdmobSize.BANNER_320x50
2.chech you have set permission in xxx-app.xml
3.Is your ad just create? The ad will not show until the id is created for 2 hours
4.showInterstitial required called after load success event.

**Comment by hypesol** [comment]
I followed your steps but conditions are same no error and no ad.

I am using admob_no_gps.ane file and using this code in xml
 <android>
        <manifestAdditions><![CDATA[<manifest>
<uses-permission android:name="android.permission.INTERNET"/>
<uses-permission android:name="android.permission.READ_PHONE_STATE"/>
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
<uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>
</manifest>]]></manifestAdditions>
    </android>

If i use the code given by you that not works gives error of "app tool failed"

and these banner codes are for testing which provided by android official team. 

I tried these codes with "pozirk" Ane and there these working fine banner and interstitial is showing fine. But I want to use your ANE thats y I am asking you.

**Comment by lilili87222** [comment]
import so.cuo.platform.admob.*;
var bannerAdUID:String = "ca-app-pub-3940256099942544/6300978111";
var intersAdUID:String = "ca-app-pub-3940256099942544/1033173712";
Admob.getInstance().setKeys(bannerAdUID,intersAdUID);
Admob.getInstance().showBanner(AdmobSize.BANNER_320x50,AdmobPosition.BOTTOM_CENTER);

Change id to what you got from admob.com

App tool failed? paste error detail here.Can admob_all_in_one works?

**Comment by ShivramAs3** [comment]
var admob:Admob= Admob.getInstance();
				extraParam=new ExtraParameter();
				extraParam.testDeviceID="true";
	//			extraParam.isChildApp=true;
				if(admob.supportDevice){
					admob.setKeys("ca-app-pub-1921270689398279/7329008842");
					//admob.showBanner(Admob.BANNER,AdmobPosition.BOTTOM_CENTER);
					admob.showBanner(AdmobSize.BANNER_320x50,AdmobPosition.BOTTOM_CENTER);
					admob.addEventListener(AdmobEvent.onBannerReceive, onAdEvent);
					admob.enableTrace=true;
					output.text="admob supported";
				}
				else
				{
					output.text = "admob not supported";
				}
				
			}
		}
		
		private function onAdEvent(event:AdmobEvent):void
		{
			if (event.type == AdmobEvent.onBannerReceive)
			{

				output.text="banner received";
			}
			
		}


I have created admob unit id yesterday .I want to test my app before publishing to play store.
There is no error in publishing apk,everything is working fine but banner is not loaded. 
I'm not getting "output.text="banner received";"

**Comment by lilili87222** [comment]
Have you config xxx-app.xml?

**Comment by ShivramAs3** [comment]
<?xml version="1.0" encoding="utf-8" standalone="no" ?>

<application xmlns="http://ns.adobe.com/air/application/26.0">
  <id>CarColorGame</id>
  <versionNumber>1.0.0</versionNumber>
  <versionLabel/>
  <filename>Car Color Game</filename>
  <description/>
  <name>Car Color Game</name>
  <copyright/>
  <initialWindow>
    <content>Car%20Color%20Games.swf</content>
    <systemChrome>standard</systemChrome>
    <transparent>false</transparent>
    <visible>true</visible>
    <fullScreen>false</fullScreen>
    <aspectRatio>portrait</aspectRatio>
    <renderMode>auto</renderMode>
    <autoOrients>false</autoOrients></initialWindow>
  <icon>
    <image72x72>smallIcon.png</image72x72>
  </icon>
  <customUpdateUI>false</customUpdateUI>
  <allowBrowserInvocation>false</allowBrowserInvocation>
  <android>
    <manifestAdditions><![CDATA[<manifest>
<uses-permission android:name="android.permission.INTERNET"/>
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
<uses-permission android:name="android.permission.READ_PHONE_STATE"/>
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
<uses-permission android:name="android.permission.CAMERA"/>
<uses-permission android:name="android.permission.DISABLE_KEYGUARD"/>
<uses-permission android:name="android.permission.WAKE_LOCK"/>
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
<uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>
</manifest>]]></manifestAdditions>
  </android>
  <supportedLanguages>en zh cs nl fr de it ja ko pl pt ru es sv tr</supportedLanguages>
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  <extensions>
    <extensionID>so.cuo.platform.admob</extensionID>
  </extensions>
</application>

**Comment by ShivramAs3** [comment]
![untitled](https://user-images.githubusercontent.com/31583798/30036111-d3422996-91cd-11e7-8636-f633c0bd6062.png)

**Comment by lilili87222** [comment]
<android>
        <manifestAdditions><![CDATA[
			<manifest android:installLocation="auto">
			    <uses-permission android:name="android.permission.INTERNET"/>
			    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
			    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>
			     <uses-permission android:name="android.permission.READ_PHONE_STATE"/>
			     <application>
 <meta-data android:name="com.google.android.gms.version"
        android:value="@integer/google_play_services_version" />
			  	   <activity android:name="com.google.android.gms.ads.AdActivity" android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|uiMode|screenSize|smallestScreenSize" android:theme="@android:style/Theme.Translucent"/>
			     </application>
			</manifest>
		]]></manifestAdditions>
    </android>

**Comment by lilili87222** [comment]
```
<android>
        <manifestAdditions><![CDATA[
			<manifest android:installLocation="auto">
			    <uses-permission android:name="android.permission.INTERNET"/>
			    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
			    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>
			     <uses-permission android:name="android.permission.READ_PHONE_STATE"/>
			     <application>
 <meta-data android:name="com.google.android.gms.version"
        android:value="@integer/google_play_services_version" />
			  	   <activity android:name="com.google.android.gms.ads.AdActivity" android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|uiMode|screenSize|smallestScreenSize" android:theme="@android:style/Theme.Translucent"/>
			     </application>
			</manifest>
		]]></manifestAdditions>
    </android>
```

**Comment by ShivramAs3** [comment]
I'm publishing apk using adobe flash cc. app,xml file is generated automatically if i edit it. I'm getting error.
![error](https://user-images.githubusercontent.com/31583798/30045872-6b0c4be8-9224-11e7-9a74-681bcf5797c9.jpg)

**Comment by nikhilreddy123456** [comment]
same Problem can any one help us

**Comment by lilili87222** [comment]
Updated

**Comment by lilili87222** [comment]
NOT able to do that
