### ISSUE TITLE
Does isChildApp sets ads to non-personalized if set to true?

### ISSUE THREAD

**Issue by sairope** [lilili87222/admob-for-flash#89]
I'm looking for a way to be able to switch between personalized and non-personalize ad requests. Does your sdk supports something like that?

I'm working on my own consent (opt-in) form (https://developers.google.com/admob/ios/eu-consent) and according to google:

The default behavior of the Google Mobile Ads SDK is to serve personalized ads. If a user has consented to receive only non-personalized ads, you can configure an GADRequest object with the following code to specify that only non-personalized ads should be returned:

GADRequest *request = [GADRequest request];
GADExtras *extras = [[GADExtras alloc] init];
extras.additionalParameters = @{@"npa": @"1"};
[request registerAdNetworkExtras:extras];

Also, does isChildAppworks as suggested in the tittle?

**Comment by lilili87222** [comment]
fixed
set param as follow.			
extraParam=new ExtraParameter();
			extraParam.testDeviceID="true";//if testing
			extraParam.isDesignedForFamilies=true;//if for families
			extraParam.nonPersonalizedAds=true;//if load non personalized ads only
			extraParam.isChildApp=true;// if is for child.
