### ISSUE TITLE
Google EU User Permission Policy

### ISSUE THREAD

**Issue by orcuncun** [lilili87222/admob-for-flash#90]
Is there an update we need to make about this permission?

**Comment by sairope** [comment]
You need to ask users to choose between personalized and non-personalized ads and then pass the correct value here:

extraParam.nonPersonalizedAds=true; //if want to load non Personalized ads set true

**Comment by orcuncun** [comment]
Thank you for your support but; I want to ask a question like this. Do you have to do this? Is there a necessity, will not ads be shown if I do not do it?
If there is a necessity, is there a link that describes it in more detail?

**Comment by lilili87222** [comment]
That is not necessity

**Comment by orcuncun** [comment]
thanks.
